apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terragon-research-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terragon-research-role
subjects:
- kind: ServiceAccount
  name: terragon-research-sa
  namespace: terragon-system
