{
  "apiVersion": "networking.k8s.io/v1",
  "kind": "Ingress",
  "metadata": {
    "name": "meta-prompt-evolution-hub-ingress",
    "namespace": "production",
    "annotations": {
      "nginx.ingress.kubernetes.io/ssl-redirect": "true",
      "cert-manager.io/cluster-issuer": "letsencrypt-prod"
    }
  },
  "spec": {
    "tls": [
      {
        "hosts": [
          "meta-prompt-hub.com"
        ],
        "secretName": "meta-prompt-evolution-hub-tls"
      }
    ],
    "rules": [
      {
        "host": "meta-prompt-hub.com",
        "http": {
          "paths": [
            {
              "path": "/",
              "pathType": "Prefix",
              "backend": {
                "service": {
                  "name": "meta-prompt-evolution-hub-service",
                  "port": {
                    "number": 80
                  }
                }
              }
            }
          ]
        }
      }
    ]
  }
}