apiVersion: v1
kind: Service
metadata:
  labels:
    app: terragon-autonomous-research
  name: terragon-autonomous-research-svc
  namespace: terragon-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: terragon-autonomous-research
  type: ClusterIP
