{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "meta-prompt-hub-service",
    "namespace": "meta-prompt-hub"
  },
  "spec": {
    "selector": {
      "app": "meta-prompt-hub"
    },
    "ports": [
      {
        "name": "http",
        "port": 80,
        "targetPort": 8000
      }
    ]
  }
}