autoscaling:
  enabled: true
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 70
image:
  pullPolicy: Always
  repository: meta-prompt-evolution-hub
  tag: latest
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - host: meta-prompt-evolution.example.com
    paths:
    - /
  tls:
  - hosts:
    - meta-prompt-evolution.example.com
    secretName: meta-prompt-evolution-tls
monitoring:
  grafana:
    enabled: true
  prometheus:
    enabled: true
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
security:
  rbac:
    enabled: true
  tls:
    enabled: true
service:
  port: 80
  targetPort: 8080
  type: ClusterIP
