apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-prompt-evolution-hub-deployment
  namespace: production
  labels:
    app: meta-prompt-evolution-hub
    version: 1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: meta-prompt-evolution-hub
  template:
    metadata:
      labels:
        app: meta-prompt-evolution-hub
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: meta-prompt-evolution-hub
        image: meta-prompt-evolution-hub:1.0.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
