alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 30s
  scrape_interval: 30s
rule_files:
- alert_rules.yml
scrape_configs:
- job_name: terragon-research-platform
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: 'true'
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scrape
