alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files:
- meta_prompt_evolution_rules.yml
scrape_configs:
- job_name: meta-prompt-evolution-hub
  metrics_path: /metrics
  scrape_interval: 30s
  static_configs:
  - targets:
    - meta-prompt-evolution-hub-service:80
- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    regex: 'true'
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
