apiVersion: v1
kind: ServiceAccount
metadata:
  name: meta-prompt-evolution-hub-sa
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meta-prompt-evolution-hub-role
  namespace: production
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meta-prompt-evolution-hub-rolebinding
  namespace: production
subjects:
- kind: ServiceAccount
  name: meta-prompt-evolution-hub-sa
  namespace: production
roleRef:
  kind: Role
  name: meta-prompt-evolution-hub-role
  apiGroup: rbac.authorization.k8s.io
