apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: meta-prompt-evolution-hpa
  namespace: meta-prompt-evolution
spec:
  maxReplicas: 20
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meta-prompt-evolution
